server:
  port: 8088

spring:
  application:
    name: kotlin-implementation
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/kotlin_kafka
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 30000
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE